### PR TITLE
Structure

### PR DESCRIPTION
**Pull request by bumbledog**
We now use a control message instead of message decorators. Most message types are tested (Non-implemented types are not)

### CODE REVIEW

**Comment by bumbledog** [comment]
Also I changed some of the projects to libararies and now apparently there are 2000 changes this can't be right help

**Review by aaronlamchops — APPROVED** [review]
Holy commit... Lots of files but it all makes sense with the amount of test projects and refactoring. 
Glad you changed the project properties to class libraries.
Nice Unit Testing. From my experience in how Dr.Clyde grades, this amount of unit testing is great! We will have to test our sending and receiving, but that wont be that much to add.
Good use of the Strategy pattern for the Message class. 
Looks good!

**Comment by aaronlamchops** [comment]
Also, the 200+ file changes might be due to adding the unit testing framework. I think its completely fine. But, lets hold off on merging until you know for sure that this is correct.

**Comment by aaronlamchops** [comment]
Yeah, it looks fine. I looked through all the files that it changed and it all makes sense with everything that was added with changes of the properties and creating unit tests.
Merging PR.

**Pull request merged**
